/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dexcomin.ecjpake;

public class ecjpake {
  public static byte[] writeRoundOneJ() {
        return ecjpakeJNI.writeRoundOneJ();
}

  public static byte[] writeRoundTwoJ() {
        return ecjpakeJNI.writeRoundTwoJ();
}

  public static byte[] getKey() {
        return ecjpakeJNI.getKey();
}

  public static void readRoundOneJ(byte[] round) {
    ecjpakeJNI.readRoundOneJ(round);
  }

  public static void readRoundTwoJ(byte[] round) {
    ecjpakeJNI.readRoundTwoJ(round);
  }

  public static void setInfo(byte[] round) {
    ecjpakeJNI.setInfo(round);
  }

  public static byte[] sayHello() {
        return ecjpakeJNI.sayHello();
}

  public static void init() {
    ecjpakeJNI.init();
  }

}
