/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dexcomin.ecjpake;

public class ecjpake {
  public static byte[] writeRoundOneJ( int Round_Number) {
      System.out.println("writeRound: "+ Round_Number);
        return ecjpakeJNI.writeRoundOneJ(Round_Number);
}

  public static byte[] writeRoundTwoJ() {
      System.out.println("write Round: 3");
        return ecjpakeJNI.writeRoundTwoJ();
}

  public static byte[] getKey() {
        return ecjpakeJNI.getKey();
}

  public static int readRoundOneJ(byte[] round, int Round_Number ) {
      System.out.println("Read Round: "+ Round_Number);
   return ecjpakeJNI.readRoundOneJ(round, round.length, Round_Number);
  }

  public static void readRoundTwoJ(byte[] round) {
      System.out.println("Read Round: 3");
      ecjpakeJNI.readRoundTwoJ(round);
  }

  public static void setInfo(byte[] round) {
    ecjpakeJNI.setInfo(round);
  }

  public static byte[] sayHello() {
        return ecjpakeJNI.sayHello();
}

  public static void init() {
    ecjpakeJNI.init();
  }

}
